version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_DATABASE}
      - TZ=Asia/Seoul
    container_name: postgres
    volumes:
      - ./postgresql.conf:/etc/postgresql.conf
      - ./pg-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: onady/dngg-frontend:${FRONTEND_VERSION:-latest}
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}

    depends_on:
      - backend
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: onady/dngg-backend:${BACKEND_VERSION:-latest}
    ports:
      - "3010:3010"
    environment:
      - NODE_ENV=prod
      - TZ=Asia/Seoul
    depends_on:
      - db
    restart: always

